---
# Configurações técnicas passadas para o pandoc, serão mescladas com as
# configurações lidas do PDF.
fontsize: 12pt
papersize: a4
# Opção hyphens passada para quebrar os links longos
classoption: openright,twoside,hyphens
documentclass: abntex2
lang: pt-BR
---
